# Generated by Django 5.1.6 on 2025-02-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_file', models.CharField(max_length=255)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_list.task')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_list.task_status')),
            ],
        ),
    ]
